server:
  port: 7000

spring:
  application:
    name: blog-hook
  mail:
    host: smtp.163.com
    username: kimnotice@163.com
    password: Kim123456
    default-encoding: utf-8
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

command:
  hexo:
    - "cd /data/kimzing-blog"
    - "git pull origin master"
    - "cd /data/kimzing-blog/blog-hexo"
    - "hexo g"